query GetSkills($searchTerm: String = "", $limit: Int = 10, $offset: Int = 0, $orderDirection: OrderDirection = DESC) @auth(level: PUBLIC, insecureReason: "Skills should be visible to everyone") {
    skills(where: {
        _or: [
            { title: { contains: $searchTerm } },
            { description: { contains: $searchTerm } },
            { category: { contains: $searchTerm } },
            { tags: { includes: $searchTerm } }
        ]
    }, 
    orderBy: [{ createdAt: $orderDirection }], 
    limit: $limit, # Maximum number of skills to return
    offset: $offset # Number of skills to skip
    ) {
        id
        title
        description
        category
        createdAt
        tags
        upvotes
        commentCount
        installCommand
        promptConfig
        usageExample
        author{
            clerkId
            email
            username
            imageUrl
        }
    }
}